[unstable]
# 需要cargo重新编译相关库
build-std = ["alloc", "core", "compiler_builtins"]

[target.'cfg(target_os = "none")']
# 使用bootimage引导
runner = "bootimage runner"

[build]
target = "target_arch/x86_64.json"
